timeout: 0
serial: yes
verbose: no
interface_branding: MindOS

/MindOS
    protocol: limine
    path: boot():/boot/mindos-kernel
    module_path: boot():/boot/initrd.img
    module_string: initrd
    resolution: 1280x800x32
    randomise_hhdm_base: no
