timeout: 0
serial: yes
verbose: no
interface_branding: MindOS
term_background: 8c1010
term_foreground: ffffff
term_background_bright: 8c1010
term_foreground_bright: ffffff

/MindOS
    protocol: limine
    path: boot():/boot/mindos-kernel
    module_path: boot():/boot/initrd.img
    module_string: initrd
    resolution: 1280x800x32
    randomise_hhdm_base: no
