# /etc/pacman.conf on the MindOS live system.
[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
ParallelDownloads = 8
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[mindos]
SigLevel = Optional TrustAll
Server = file:///var/lib/mindos/repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
